# mkdocs.yml
site_name: "Crater Bible Project"
site_url: https://crater.voyagerlabs.tech/
site_author: Eyetu Kingsley
site_description: Open Source Scripture Projection Software for Churches
theme:
  name: shadcn
  show_title: true
  show_stargazers: true
  pygments_style:
        light: shadcn-light
        dark: github-dark 
  icon: img/logo-black.svg
  topbar_sections: false
  katex_options:
    macros: #Â example of macros
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"
  show_datetime: false 
repo_name: crater
repo_url: https://github.com/CodeKing12/crater